---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "crawler.fullname" . }}
  labels:
    app: crawler
    component: crawler
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
      component: crawler
      release: {{ .Release.Name }}
  template:
    metadata:
      name: crawler
      labels:
        app: crawler
        component: crawler
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: crawler
        env:
        - name: MONGO
          value: {{ .Values.databaseHost | default (printf "%s-mongodb" .Release.Name) }}
        - name: MONGO_PORT
          value: "27017"
        - name: RMQ_HOST
          value: {{ .Values.queueHost | default (printf "%s-rabbitmq" .Release.Name) }}
        - name: RMQ_QUEUE
          value: derp
        - name: RMQ_USERNAME
          value: admin
        - name: RMQ_PASSWORD
          value: admin
        - name: CHECK_INTERVAL
          value: "60"
        - name: EXCLUDE_URLS
          value: '.*github.com'
