---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "ui.fullname" . }}
  labels:
    app: crawler
    component: ui-crawler
    release: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: crawler
      component: ui-crawler
      release: {{ .Release.Name }}
  template:
    metadata:
      name: ui-crawler-pod
      labels:
        app: crawler
        component: ui-crawler
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: ui-crawler
        ports:
        - containerPort: 8000
          name: ui-crawler
          protocol: TCP
        env:
        - name: MONGO
          value: {{ .Values.databaseHost | default (printf "%s-mongodb" .Release.Name) }}
        - name: MONGO_PORT
          value: "27017"
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
