---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "rabbitmq.fullname" . }}
  labels:
    app: crawler
    component: rabbitmq
    release: {{ .Release.Name }}
spec:
  type: LoadBalancer
  ports:
  - name: rabbitmq
#    nodePort: 30136
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: manager
#    nodePort: 32699
    port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    app: crawler
    component: rabbitmq
    release: {{ .Release.Name }}
