---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: crawler-mongo-disk
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    fsType: "ext4" 
    pdName: "crawler-mongo-disk"

